AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create Secret Manager secret for mortgage agents IDs'

Resources:
  MortgageAgentsIdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: mortgage_agents
      Description: Secret containing IDs and aliases for mortgage agents
      SecretString: |
      {
        "single_agent_id":"",
        "single_agent_alias":"",
        "multi_agent_id":"",
        "multi_agent_alias":""
      }

Outputs:
  MortgageAgentsIdsSecretArn:
    Description: ARN of the Secret Manager secret containing mortgage agents IDs
    Value: !Ref MortgageAgentsIdsSecret